// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_msg_id.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cs_5fmsg_5fid_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cs_5fmsg_5fid_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cs_5fmsg_5fid_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cs_5fmsg_5fid_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cs_5fmsg_5fid_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace pb {

enum eClient2GameMsgId : int {
  cs_engine_min_msg_id = 0,
  c2s_client_session_ping_id = 1,
  s2c_client_session_pong_id = 2,
  sc_engine_min_msg_id = 299,
  cs_logic_min_msg_id = 300,
  cs_account_register_req_id = 301,
  sc_account_register_ack_id = 302,
  cs_account_login_req_id = 303,
  sc_account_login_ack_id = 304,
  cs_game_login_req_id = 305,
  sc_game_login_ack_id = 306,
  cs_create_player_req_id = 307,
  sc_create_player_ack_id = 308,
  cs_select_player_req_id = 309,
  sc_select_player_ack_id = 310,
  cs_exit_game_req_id = 311,
  cs_reconnect_game_req_id = 312,
  sc_reconnect_game_ack_id = 313,
  sc_server_time_ntf_id = 314,
  cs_gm_req_id = 315,
  sc_tip_ntf_id = 316,
  sc_errorcode_ntf_id = 317,
  sc_logic_max_msg_id = 65535,
  eClient2GameMsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  eClient2GameMsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool eClient2GameMsgId_IsValid(int value);
constexpr eClient2GameMsgId eClient2GameMsgId_MIN = cs_engine_min_msg_id;
constexpr eClient2GameMsgId eClient2GameMsgId_MAX = sc_logic_max_msg_id;
constexpr int eClient2GameMsgId_ARRAYSIZE = eClient2GameMsgId_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* eClient2GameMsgId_descriptor();
template<typename T>
inline const std::string& eClient2GameMsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, eClient2GameMsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function eClient2GameMsgId_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    eClient2GameMsgId_descriptor(), enum_t_value);
}
inline bool eClient2GameMsgId_Parse(
    const std::string& name, eClient2GameMsgId* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<eClient2GameMsgId>(
    eClient2GameMsgId_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::pb::eClient2GameMsgId> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pb::eClient2GameMsgId>() {
  return ::pb::eClient2GameMsgId_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cs_5fmsg_5fid_2eproto
